org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3,]
neo_version=26.3.0.22-beta

# Mod Properties
mod_id=cinchsvillagerstatues
mod_name=Cinch's Villager Statues
mod_license=MIT
mod_version=3.8.0
mod_group_id=net.cinchtail.cinchsvillagerstatues
mod_authors=Cinchtail
mod_description=Statues of villagers can be found around the world.

## Links
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/cinchs-villager-statues
mod_sources=https://github.com/cinchtail/Cinchs_Villager_Statues
mod_curseforge=https://www.curseforge.com/members/cinchtail/projects
mod_modrinth=https://modrinth.com/user/cinchtail
mod_discord=https://discord.gg/aBBz7E52Jy
mod_kofi=https://ko-fi.com/cinchtail
mod_youtube=https://www.youtube.com/@CinchPlaysMC